name: variable workflow
on:
  workflow_dispatch:

env:
  MY_VAR: "This is a custom environment variable"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo " ======Printing====builtin variables====="
          env
          pwd
          ls -lhtr
          echo " ======Printing====custom variable====="
          echo "my variable is $MY_VAR"